ServerRoot "/usr"
Listen 8088

LoadModule mpm_prefork_module /usr/libexec/apache2/mod_mpm_prefork.so
LoadModule unixd_module /usr/libexec/apache2/mod_unixd.so
LoadModule authz_core_module /usr/libexec/apache2/mod_authz_core.so
LoadModule dir_module /usr/libexec/apache2/mod_dir.so
LoadModule mime_module /usr/libexec/apache2/mod_mime.so
LoadModule alias_module /usr/libexec/apache2/mod_alias.so

ServerName localhost:8088
DocumentRoot "/Users/onlymec/Documents/OST/Practical/Practical-6/apache-php"

<Directory "/Users/onlymec/Documents/OST/Practical/Practical-6/apache-php">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

Alias /Practical-6/ "/Users/onlymec/Documents/OST/Practical/Practical-6/apache-php/"

DirectoryIndex index.php index.html
TypesConfig /private/etc/apache2/mime.types
PidFile /tmp/httpd_ost_prac6.pid
ErrorLog /tmp/httpd_ost_prac6_error.log
